<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Pattern</string>
    <key>file_extensions</key>
    <array>
      <string>pattern</string>
    </array>
    <key>scope</key>
    <string>source.pattern</string>
    <key>contexts</key>
    <dict>
      <key>main</key>
      <array>
        <dict>
          <key>match</key>
          <string>^Needs</string>
          <key>scope</key>
          <string>storage.type.namespace.pattern</string>
        </dict>
      </array>
    </dict>
  </dict>
</plist>